db:
  database: warriorfit
  host: 78.21.255.210
  password: ranger14
  port: 5432
  username: benoi
display:
  darkmode: false
hr:
  url: http://127.0.0.1:8005/api/v1/phef/test
mail:
  host: 192.168.0.174
  password: R@nger&1401!
  port: 25
  sender: benoit@albatros.be
  sender_email: benoit@albatros.be
  use_ssl: false
  use_tls: false
  username: benoit
path:
  pdf_path: /tmp/pdf
unit:
  name: 3PARA
version:
  number: 0.1.0
  status: development
