"""update testsession times

Revision ID: 09a887bcf10b
Revises: c1ec22624d97
Create Date: 2025-09-21 15:33:40.590302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a887bcf10b'
down_revision: Union[str, Sequence[str], None] = 'c1ec22624d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fitness_tests', 'passed')
    op.add_column('phef_tests', sa.Column('sideBridge_r', sa.Float(), nullable=False))
    op.add_column('phef_tests', sa.Column('sideBridge_l', sa.Float(), nullable=False))
    op.add_column('phef_tests', sa.Column('pointBridge_r', sa.Integer(), nullable=False))
    op.add_column('phef_tests', sa.Column('pointBridge_l', sa.Integer(), nullable=False))
    op.add_column('phef_tests', sa.Column('pointsRunning', sa.Integer(), nullable=False))
    op.drop_column('phef_tests', 'planking_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phef_tests', sa.Column('planking_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('phef_tests', 'pointsRunning')
    op.drop_column('phef_tests', 'pointBridge_l')
    op.drop_column('phef_tests', 'pointBridge_r')
    op.drop_column('phef_tests', 'sideBridge_l')
    op.drop_column('phef_tests', 'sideBridge_r')
    op.add_column('fitness_tests', sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
