"""baseline schema

Revision ID: 1263e3d648be
Revises: 
Create Date: 2025-12-02 10:35:37.549973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1263e3d648be'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('march',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_number', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('datetime_executed', postgresql.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_march_service_number'), 'march', ['service_number'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('service_men', 'rank',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_men', 'rank',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('reservations')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_march_service_number'), table_name='march')
    op.drop_table('march')
    # ### end Alembic commands ###
