"""Initial migration

Revision ID: 208ad04dd4c1
Revises: 
Create Date: 2025-09-17 14:33:31.545174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '208ad04dd4c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_tests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('test_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number_pti', sa.String(length=50), nullable=True),
    sa.Column('datetime_start', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('type_test', sa.Enum('PHEF', 'COMBAT', 'FUNCTIONAL', name='typefitnesstest'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number_pti')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'GUEST', 'PTI', 'PLANNER', 'APTI', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('serial_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combat_swimming_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('swim_paased', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fitness_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('combat_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running_time', sa.Float(), nullable=False),
    sa.Column('obstacle_passed', sa.Boolean(), nullable=False),
    sa.Column('rope_passed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fitness_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('functional_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('push_ups', sa.Integer(), nullable=False),
    sa.Column('sit_ups', sa.Integer(), nullable=False),
    sa.Column('pull_ups', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fitness_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phef_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('running_time', sa.Float(), nullable=False),
    sa.Column('planking_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['fitness_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_fitness_tests',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('fitness_test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fitness_test_id'], ['fitness_tests.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'fitness_test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_fitness_tests')
    op.drop_table('phef_tests')
    op.drop_table('functional_tests')
    op.drop_table('combat_tests')
    op.drop_table('combat_swimming_tests')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('test_sessions')
    op.drop_table('fitness_tests')
    # ### end Alembic commands ###
