"""update auditlog

Revision ID: 5725be57b291
Revises: 82ce4ccdc85f
Create Date: 2025-10-28 17:38:35.419239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5725be57b291'
down_revision: Union[str, Sequence[str], None] = '82ce4ccdc85f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
