"""update testsession

Revision ID: c1ec22624d97
Revises: 208ad04dd4c1
Create Date: 2025-09-17 18:41:04.865785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ec22624d97'
down_revision: Union[str, Sequence[str], None] = '208ad04dd4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('test_sessions_serial_number_pti_key'), 'test_sessions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('test_sessions_serial_number_pti_key'), 'test_sessions', ['serial_number_pti'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
