"""update servicemen

Revision ID: d055d56be1a8
Revises: 3464ba89da97
Create Date: 2025-11-06 08:50:09.069605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd055d56be1a8'
down_revision: Union[str, Sequence[str], None] = '3464ba89da97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_location', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_units_name')
    )
    op.create_table('service_men',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('mail', sa.String(length=120), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('service_number', sa.String(length=50), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('para', sa.Boolean(), nullable=False),
    sa.Column('ops_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail', name='uq_service_men_mail'),
    sa.UniqueConstraint('service_number', name='uq_service_men_service_number')
    )
    op.create_index(op.f('ix_service_men_unit_id'), 'service_men', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_men_unit_id'), table_name='service_men')
    op.drop_table('service_men')
    op.drop_table('units')
    # ### end Alembic commands ###
