"""update servicemen mail

Revision ID: e36323e18483
Revises: d055d56be1a8
Create Date: 2025-11-06 09:12:39.195695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e36323e18483'
down_revision: Union[str, Sequence[str], None] = 'd055d56be1a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_service_men_mail'), 'service_men', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_service_men_mail'), 'service_men', ['mail'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
