db:
  host: "78.21.255.210"
  port: 5432
  database : "warriorfit"
  username : "benoi"
  password : "ranger14"
path:
  pdf_path : "/home/benoit/temp"
unit:
  name : "1-3 Bn Lanciers"
mail:
  host : "smtp.gmail.com"
  port : 587
  username : ""
  password : ""
  sender : ""
  use_tls: False
  use_ssl: False
  sender_email : ""




