db:
  host: "192.168.0.30"
  port: 5432
  database : "warriorfit"
  username : "benoi"
  password : "ranger14"
path:
  pdf_path : "/home/benoit/temp"
unit:
  name : "1-3 Bn Lanciers"
mail:
  host : "192.168.0.174"
  port : 25
  username : "benoit"
  password : "R@nger&1401!"
  sender : "benoit@albatros.be"
  use_tls: False
  use_ssl: False
  sender_email : "benoit@albatros.be"




