@startuml
skinparam rectangle {
  BackgroundColor<<Process>> LightBlue
  BackgroundColor<<DataStore>> LightYellow
  BackgroundColor<<External>> LightGray
}

rectangle "Gebruiker" <<External>> as User
rectangle "Controllers" <<Process>> as Controllers
rectangle "Services" <<Process>> as Services
rectangle "Database" <<DataStore>> as DB
rectangle "PDF-generator" <<Process>> as PDFGen
rectangle "Mailservice" <<Process>> as Mail

' Data flows
User --> Controllers : "Voer testresultaten in"
Controllers --> Services : "Stuur data"
Services --> DB : "Sla resultaten op"

Services --> Mail : "send mail met resultaten"


@enduml
