@startuml
title Fysische Testen - WARRIORFIT
left to right direction
skinparam packageStyle rectangle
skinparam usecasePadding 10
skinparam actorMargin 40

actor PTI

package "PHEF Testen" {
  usecase "PHEF invoeren" as UC001
  usecase "PHEF overzicht" as UC0011
  usecase "PHEF aanpassen" as UC0012
  usecase "PHEF verwijderen" as UC0013
}

package "Combat Testen" {
  usecase "Combat invoeren" as UC002
  usecase "Combat overzicht" as UC0021
  usecase "Combat aanpassen" as UC0022
  usecase "Combat verwijderen" as UC0023
}

package "ZEM Testen" {
  usecase "ZEM invoeren" as UC003
  usecase "ZEM overzicht" as UC0031
  usecase "ZEM aanpassen" as UC0032
  usecase "ZEM verwijderen" as UC0033
}

package "Functionele Testen" {
  usecase "Functioneel invoeren" as UC004
  usecase "Functioneel overzicht" as UC0041
  usecase "Functioneel aanpassen" as UC0042
  usecase "Functioneel verwijderen" as UC0043
}

PTI --> UC001
PTI --> UC0011
PTI --> UC0012
PTI --> UC0013
PTI --> UC002
PTI --> UC0021
PTI --> UC0022
PTI --> UC0023
PTI --> UC003
PTI --> UC0031
PTI --> UC0032
PTI --> UC0033
PTI --> UC004
PTI --> UC0041
PTI --> UC0042
PTI --> UC0043
@enduml