@startuml
title Systeemservices / Monitoring - WARRIORFIT
left to right direction
skinparam packageStyle rectangle
skinparam usecasePadding 10

actor Admin
actor Systeem

package "Monitoring & Services" {
  usecase "Status services / monitoring" as UC013
}

Admin --> UC013
Systeem --> UC013
@enduml