<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="results">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="race" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="athlete" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="bib" type="xs:string"/>
                    <xs:element name="name" type="xs:string"/>
                    <xs:element name="category" type="xs:string"/>
                    <xs:element name="start" type="xs:dateTime" minOccurs="0"/>
                    <xs:element name="finish" type="xs:dateTime"/>
                    <xs:element name="net" type="xs:string"/>
                    <xs:element name="rank" type="xs:int"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="name" type="xs:string" use="required"/>
            <xs:attribute name="date" type="xs:date" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>